/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasury,
  ITreasuryInterface,
} from "../../../contracts/ForgeQuestManager.sol/ITreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expectedStakeAmount",
        type: "uint256",
      },
    ],
    name: "lockStake",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expectedRewardAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expectedStakeAmount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "reason",
        type: "bytes32",
      },
    ],
    name: "refundQuest",
    outputs: [
      {
        internalType: "uint256",
        name: "refundedStakeAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "reserveReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expectedRewardAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expectedStakeAmount",
        type: "uint256",
      },
    ],
    name: "settleQuestPayout",
    outputs: [
      {
        internalType: "uint256",
        name: "totalPayout",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITreasury__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryInterface {
    return new Interface(_abi) as ITreasuryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITreasury {
    return new Contract(address, _abi, runner) as unknown as ITreasury;
  }
}
