/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ForgeQuestManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCEPTANCE_FEE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_QUEST_DURATION"
      | "MAX_SINGLE_REWARD"
      | "VERIFIER_ROLE"
      | "acceptQuest"
      | "cancelQuest"
      | "claimReward"
      | "createQuest"
      | "getRoleAdmin"
      | "grantRole"
      | "grantVerifier"
      | "hasRole"
      | "nextQuestId"
      | "owner"
      | "pause"
      | "pauseRewardSystem"
      | "paused"
      | "playerNonces"
      | "playerQuestIndices"
      | "proofHashToQuestId"
      | "quests"
      | "renounceOwnership"
      | "renounceRole"
      | "reputation"
      | "revokeRole"
      | "revokeVerifier"
      | "rewardNFT"
      | "rewardSystemHealthy"
      | "setTreasury"
      | "submitQuest"
      | "supportsInterface"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "unpauseRewardSystem"
      | "usedProofHashes"
      | "verifyQuest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircuitBreakerTriggered"
      | "OwnershipTransferred"
      | "Paused"
      | "QuestAccepted"
      | "QuestCreated"
      | "QuestRewarded"
      | "QuestSubmitted"
      | "QuestVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCEPTANCE_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_QUEST_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SINGLE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createQuest",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextQuestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseRewardSystem",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerQuestIndices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proofHashToQuestId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rewardNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardSystemHealthy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuest",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unpauseRewardSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedProofHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyQuest",
    values: [BigNumberish, boolean, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCEPTANCE_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_QUEST_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SINGLE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextQuestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseRewardSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerQuestIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofHashToQuestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewardNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardSystemHealthy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpauseRewardSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedProofHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyQuest",
    data: BytesLike
  ): Result;
}

export namespace CircuitBreakerTriggeredEvent {
  export type InputTuple = [reason: string];
  export type OutputTuple = [reason: string];
  export interface OutputObject {
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestAcceptedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    player: AddressLike,
    acceptedAt: BigNumberish
  ];
  export type OutputTuple = [
    questId: bigint,
    player: string,
    acceptedAt: bigint
  ];
  export interface OutputObject {
    questId: bigint;
    player: string;
    acceptedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestCreatedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    creator: AddressLike,
    title: string,
    rewardAmount: BigNumberish,
    xpReward: BigNumberish
  ];
  export type OutputTuple = [
    questId: bigint,
    creator: string,
    title: string,
    rewardAmount: bigint,
    xpReward: bigint
  ];
  export interface OutputObject {
    questId: bigint;
    creator: string;
    title: string;
    rewardAmount: bigint;
    xpReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestRewardedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    player: AddressLike,
    rewardAmount: BigNumberish,
    xpReward: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    questId: bigint,
    player: string,
    rewardAmount: bigint,
    xpReward: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    questId: bigint;
    player: string;
    rewardAmount: bigint;
    xpReward: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestSubmittedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    player: AddressLike,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    questId: bigint,
    player: string,
    proofHash: string
  ];
  export interface OutputObject {
    questId: bigint;
    player: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestVerifiedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    player: AddressLike,
    success: boolean,
    rewardAmount: BigNumberish,
    xpReward: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    questId: bigint,
    player: string,
    success: boolean,
    rewardAmount: bigint,
    xpReward: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    questId: bigint;
    player: string;
    success: boolean;
    rewardAmount: bigint;
    xpReward: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [
    previousTreasury: AddressLike,
    newTreasury: AddressLike
  ];
  export type OutputTuple = [previousTreasury: string, newTreasury: string];
  export interface OutputObject {
    previousTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ForgeQuestManager extends BaseContract {
  connect(runner?: ContractRunner | null): ForgeQuestManager;
  waitForDeployment(): Promise<this>;

  interface: ForgeQuestManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCEPTANCE_FEE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_QUEST_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_SINGLE_REWARD: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptQuest: TypedContractMethod<[questId: BigNumberish], [void], "payable">;

  cancelQuest: TypedContractMethod<
    [questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimReward: TypedContractMethod<
    [questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createQuest: TypedContractMethod<
    [
      title: string,
      metadataUri: string,
      rewardAmount: BigNumberish,
      xpReward: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [void],
    "payable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nextQuestId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauseRewardSystem: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  playerNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  playerQuestIndices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  proofHashToQuestId: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  quests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string
      ] & {
        questId: bigint;
        creator: string;
        title: string;
        metadataUri: string;
        proofUri: string;
        proofHash: string;
        stakeAmount: bigint;
        rewardAmount: bigint;
        xpReward: bigint;
        createdAt: bigint;
        startedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        player: string;
        playerNonce: bigint;
        proofVerificationHash: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  reputation: TypedContractMethod<[], [string], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  rewardNFT: TypedContractMethod<[], [string], "view">;

  rewardSystemHealthy: TypedContractMethod<[], [boolean], "view">;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  submitQuest: TypedContractMethod<
    [questId: BigNumberish, proofUri: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unpauseRewardSystem: TypedContractMethod<[], [void], "nonpayable">;

  usedProofHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyQuest: TypedContractMethod<
    [questId: BigNumberish, success: boolean, proofVerificationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCEPTANCE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_QUEST_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SINGLE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptQuest"
  ): TypedContractMethod<[questId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelQuest"
  ): TypedContractMethod<[questId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[questId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createQuest"
  ): TypedContractMethod<
    [
      title: string,
      metadataUri: string,
      rewardAmount: BigNumberish,
      xpReward: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextQuestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseRewardSystem"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "playerNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerQuestIndices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofHashToQuestId"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "quests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string
      ] & {
        questId: bigint;
        creator: string;
        title: string;
        metadataUri: string;
        proofUri: string;
        proofHash: string;
        stakeAmount: bigint;
        rewardAmount: bigint;
        xpReward: bigint;
        createdAt: bigint;
        startedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        player: string;
        playerNonce: bigint;
        proofVerificationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardSystemHealthy"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQuest"
  ): TypedContractMethod<
    [questId: BigNumberish, proofUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseRewardSystem"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedProofHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyQuest"
  ): TypedContractMethod<
    [questId: BigNumberish, success: boolean, proofVerificationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CircuitBreakerTriggered"
  ): TypedContractEvent<
    CircuitBreakerTriggeredEvent.InputTuple,
    CircuitBreakerTriggeredEvent.OutputTuple,
    CircuitBreakerTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "QuestAccepted"
  ): TypedContractEvent<
    QuestAcceptedEvent.InputTuple,
    QuestAcceptedEvent.OutputTuple,
    QuestAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "QuestCreated"
  ): TypedContractEvent<
    QuestCreatedEvent.InputTuple,
    QuestCreatedEvent.OutputTuple,
    QuestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "QuestRewarded"
  ): TypedContractEvent<
    QuestRewardedEvent.InputTuple,
    QuestRewardedEvent.OutputTuple,
    QuestRewardedEvent.OutputObject
  >;
  getEvent(
    key: "QuestSubmitted"
  ): TypedContractEvent<
    QuestSubmittedEvent.InputTuple,
    QuestSubmittedEvent.OutputTuple,
    QuestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuestVerified"
  ): TypedContractEvent<
    QuestVerifiedEvent.InputTuple,
    QuestVerifiedEvent.OutputTuple,
    QuestVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CircuitBreakerTriggered(string)": TypedContractEvent<
      CircuitBreakerTriggeredEvent.InputTuple,
      CircuitBreakerTriggeredEvent.OutputTuple,
      CircuitBreakerTriggeredEvent.OutputObject
    >;
    CircuitBreakerTriggered: TypedContractEvent<
      CircuitBreakerTriggeredEvent.InputTuple,
      CircuitBreakerTriggeredEvent.OutputTuple,
      CircuitBreakerTriggeredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "QuestAccepted(uint256,address,uint256)": TypedContractEvent<
      QuestAcceptedEvent.InputTuple,
      QuestAcceptedEvent.OutputTuple,
      QuestAcceptedEvent.OutputObject
    >;
    QuestAccepted: TypedContractEvent<
      QuestAcceptedEvent.InputTuple,
      QuestAcceptedEvent.OutputTuple,
      QuestAcceptedEvent.OutputObject
    >;

    "QuestCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;
    QuestCreated: TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;

    "QuestRewarded(uint256,address,uint256,uint256,bytes32)": TypedContractEvent<
      QuestRewardedEvent.InputTuple,
      QuestRewardedEvent.OutputTuple,
      QuestRewardedEvent.OutputObject
    >;
    QuestRewarded: TypedContractEvent<
      QuestRewardedEvent.InputTuple,
      QuestRewardedEvent.OutputTuple,
      QuestRewardedEvent.OutputObject
    >;

    "QuestSubmitted(uint256,address,bytes32)": TypedContractEvent<
      QuestSubmittedEvent.InputTuple,
      QuestSubmittedEvent.OutputTuple,
      QuestSubmittedEvent.OutputObject
    >;
    QuestSubmitted: TypedContractEvent<
      QuestSubmittedEvent.InputTuple,
      QuestSubmittedEvent.OutputTuple,
      QuestSubmittedEvent.OutputObject
    >;

    "QuestVerified(uint256,address,bool,uint256,uint256,bytes32)": TypedContractEvent<
      QuestVerifiedEvent.InputTuple,
      QuestVerifiedEvent.OutputTuple,
      QuestVerifiedEvent.OutputObject
    >;
    QuestVerified: TypedContractEvent<
      QuestVerifiedEvent.InputTuple,
      QuestVerifiedEvent.OutputTuple,
      QuestVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
