/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lockStake"
      | "refundQuest"
      | "reserveReward"
      | "settleQuestPayout"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lockStake",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundQuest",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveReward",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleQuestPayout",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "lockStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleQuestPayout",
    data: BytesLike
  ): Result;
}

export interface ITreasury extends BaseContract {
  connect(runner?: ContractRunner | null): ITreasury;
  waitForDeployment(): Promise<this>;

  interface: ITreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lockStake: TypedContractMethod<
    [
      questId: BigNumberish,
      player: AddressLike,
      expectedStakeAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  refundQuest: TypedContractMethod<
    [
      questId: BigNumberish,
      recipient: AddressLike,
      expectedRewardAmount: BigNumberish,
      expectedStakeAmount: BigNumberish,
      reason: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  reserveReward: TypedContractMethod<
    [questId: BigNumberish, creator: AddressLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleQuestPayout: TypedContractMethod<
    [
      questId: BigNumberish,
      player: AddressLike,
      expectedRewardAmount: BigNumberish,
      expectedStakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lockStake"
  ): TypedContractMethod<
    [
      questId: BigNumberish,
      player: AddressLike,
      expectedStakeAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "refundQuest"
  ): TypedContractMethod<
    [
      questId: BigNumberish,
      recipient: AddressLike,
      expectedRewardAmount: BigNumberish,
      expectedStakeAmount: BigNumberish,
      reason: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveReward"
  ): TypedContractMethod<
    [questId: BigNumberish, creator: AddressLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleQuestPayout"
  ): TypedContractMethod<
    [
      questId: BigNumberish,
      player: AddressLike,
      expectedRewardAmount: BigNumberish,
      expectedStakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
