-- Prisma migration for QuestStatus enum update
ALTER TYPE "QuestStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "QuestStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "QuestStatus" ADD VALUE IF NOT EXISTS 'CLAIMABLE';
ALTER TYPE "QuestStatus" ADD VALUE IF NOT EXISTS 'REWARDED';
